Adding in logD Analysis scripts, data and plots
samplchallenges/SAMPL8 pull request #51
Opened 2022-09-05 19:38 UTC by aakankschit

logD analysis files were added

2022-09-07 00:09 UTC, davidlmobley requested changes
Comments other than those elsewhere:
- Right now we have no correlation metrics in the Error_plots directory; would it be straightforward to re-add? I'm not totally clear why these were dropped (though they DO appear on the submissions in the `Performance_stats_by_submission` stuff on the correlation plots
- It's not clear that there's a README file anywhere which explains the subdirectory within `Error_plots`, e.g. what is the `Perforamnce_stats_by_sol_combo` directory?
- Likewise is there something that explains `Performance_stats_by_solvent_combo` vs `Performance_stats_by_submission`? ALMOST self-explanatory, but usually I like to have a base level README.md that at least has a manifest explaining what's what.


The other comment is that if I were browsing this repo trying to figure out who did how well/what statistics to use in comparing methods, I don't see much/any guidance as to what to use. There's a lot of data here, but I might feel lost.

Probably we need to explain somewhere what we actually decided to analyze, and what comparisons can be done in a meaningful way... How many submissions had which solvent combinations? Why have we broken out solvent combinations the way we have? Similar to the other PR -- why did we make the choices we made/what choices did we make? Needs to be documented without reading the code.

2022-09-13 22:56 UTC, aakankschit commented
@davidlmobley I have added readme files to each of the plot directories please review and let me know if that looks good.

2022-09-13 22:59 UTC, aakankschit commented on physical_properties/logD/analysis/README.md
> +- [`Submissions_edited`](Submissions_edited/) - Directory that contains edited submissions. There were certain submissions that required a few manual edits. These submissions included NadinUlrich and
I am not sure how best to explain this since when I was constructing my data frame with all of the submission data that single data point kept throwing it off since it was expecting the same molecules per solvent combination to construct the pandas dataframe. It also did not make much sense to have the same number associated with a single compound as the dataset for that specific solvent combination for that specific submission to be bench marked against submissions that contained multiple compounds per submission.

2022-09-22 23:46 UTC, davidlmobley commented on physical_properties/logD/analysis/README.md
> +- [`Submissions_edited`](Submissions_edited/) - Directory that contains edited submissions. There were certain submissions that required a few manual edits. These submissions included NadinUlrich and
I am not objecting to what you did, just your grammar in explaining it. Your language does not make it clear what couldn't be benchmarked.

I think what you mean is something like, "We removed predictions for SAMPL8-1 from these submissions, because they contained only predictions for this specific compound and no others. This made it impossible to compare performance of these submissions with that of methods which had predictions for multiple compounds." Is that it? Feel free to edit.

2022-09-22 23:52 UTC, davidlmobley commented on physical_properties/logD/analysis/analysis_all/Performance_stats_by_submission/README.md
> +This folder contains plots generated by analysis for each submission that contaians correlation performance statistics for each submission along with absolute error plots
Grammar problems here; "by analysis for each submission that contaians correlation..." (also spelling mistake on contains). What contains what? The folder contains plots and correlation performance statistics? Plots OF correlation performance statistics?

I THINK you mean "This folder contains plots of performance statistics for each submission, along with absolute error plots," or something like that?

2022-09-22 23:53 UTC, davidlmobley commented on physical_properties/logD/analysis/analysis_all/README.md
> +This folder contains plots generated by analysis across all submissions. The analysis was divided into two parts, the first by submission which contaians correlation performance statistics for each s
Spelling of "contains" (first instance) not correct.

2022-09-22 23:54 UTC, davidlmobley commented on physical_properties/logD/analysis/analysis_ranked/Performance_stats_by_submission/README.md
> +This folder contains plots generated by analysis for each ranked submission that contaians correlation performance statistics for each submission along with absolute error plots
"contaians" -> "contains".

(Simpler grammar would have been, "This folder gives plots of correlation performance statistics and absolute error for each ranked submission," or something similar. But since you've used basically the same language in each case it's not really necessary to change it everywhere. You just made it more cumbersome than it had to be.)

2022-09-22 23:54 UTC, davidlmobley commented on physical_properties/logD/analysis/analysis_ranked/README.md
> +This folder contains plots generated by analysis across all ranked submissions. The analysis was divided into two parts, the first by submission which contaians correlation performance statistics for
Same spelling mistake again.

2022-09-22 23:56 UTC, davidlmobley requested changes
Mostly looks good but needs a few minor changes. Also -- the changelog said you deleted the `logD_analysis.py` script and the `submission.py` script; intentional? (I haven't checked file tree, perhaps this was just a reorganization.)

2022-09-26 20:15 UTC, aakankschit commented
> 

I deleted these files since they were from SAMPL7 analysis that had been copied to the folder and I did not use them in this analysis.

2022-09-28 22:27 UTC, davidlmobley commented on physical_properties/logD/analysis/analysis_all/Performance_stats_by_submission/README.md
> +This folder contains plots generated by analysis for each submission that contaians correlation performance statistics for each submission along with absolute error plots
You still have a "contaians" typo here.

2022-09-28 22:29 UTC, davidlmobley approved these changes
These changes look good.

2022-09-28 22:30 UTC, davidlmobley commented on physical_properties/logD/analysis/README.md
>  ## Mainifest
"Mainifest"

2022-09-28 22:40 UTC, merged