pka macrostate analysis
samplchallenges/SAMPL8 pull request #54
Opened 2023-08-15 05:27 UTC by aakankschit

Adding selected transition state analysis and updated plots.

2023-09-15 16:21 UTC, davidlmobley requested changes
I noted a few issues with some of the files/documentation, so please update/clarify those.

Also, you don't seem to have touched the main README.md at the repo level; this should be updated to add the fact that you've added the analysis, explain what you changed, add dates, etc. Typically this means at least:
- Update the changelog
- Update the text in one or more places to make clear that the analysis is now available

If there are README files that need updating slightly further into the hierarchy (e.g. physical_properties/README.md) please also update those; the idea is that you want to do a check that all the documentation relating to this challenge is now current up to this PR having een merged.

2023-09-15 16:21 UTC, davidlmobley commented on physical_properties/pKa/macrostate_analysis/README.md
> +The selected transitions were compiled based on the following assumptions while looking at the pH log-solubility curves-
I would make sure you clearly and separately explain the "selected transitions" and "popular transitions" methods, in separate paragraphs (again, refer to the type of stuff we did in the paper). Right now they are stuck together in a single paragraph and which text refers to which is a bit murky.

2023-10-04 18:05 UTC, aakankschit commented on physical_properties/pKa/macrostate_analysis/README.md
> +The selected transitions were compiled based on the following assumptions while looking at the pH log-solubility curves-
I have separated them into different paragraphs for better clarity.

2023-10-04 18:10 UTC, aakankschit commented on physical_properties/pKa/macrostate_analysis/README.md
> +* pKa values that are lesser than the ph of the lowest point of the log-solubility are treated as basic with a formal charge of +1
Done! 👍

2023-10-04 18:53 UTC, aakankschit commented on physical_properties/pKa/macrostate_analysis/selected_transitions.csv
> +Molecule ID, Experimental pKa, Formal Charge
I am updating the column header to be more detailed.

2023-10-19 17:09 UTC, davidlmobley commented on physical_properties/pKa/macrostate_analysis/selected_transitions.csv
> +Molecule ID, Experimental pKa, Formal Charge
Unless I'm missing something (and I'm fairly sure I'm not, as I'm directly inspecting the file in the current version of `selected_transitions.csv`), @aakankschit , this is not showing as changed...  The header on the file is still exactly the same as before.

2023-10-19 17:18 UTC, davidlmobley requested changes
This is almost done, except it looks like there are still two outstanding issues I've noticed:
1) You need to update the description of the pull request, and probably even its title, to make clear the scope of the changes here. Right now the PR description is just "adding selected transition state analysis and updated plots" but if I understand correctly this also completely re-does the popular transition state analysis, fixing earlier errors. This is a huge change since it means anyone using the earlier plots/analysis now needs to switch, so it needs to be reflected prominently in the pull request title, description, and in a separate entry in the top-level README.md that explains that this corrects problems with the earlier analysis and statistics.
2) You missed fixing one of the issues I raised previously, see here: https://github.com/samplchallenges/SAMPL8/pull/54#discussion_r1327524074

2023-10-19 18:53 UTC, aakankschit commented on physical_properties/pKa/macrostate_analysis/selected_transitions.csv
> +Molecule ID, Experimental pKa, Formal Charge
I forgot that the column headers had to be preserved so that I did not have to make any changes to the analysis code. Instead I have added a note in the readme files for the folders that contain the csv files for selected and popular transitions that "formal Charge" represents the charged state being transitioned to. Apologies for that confusion.

2023-10-24 21:47 UTC, davidlmobley commented
I edited the title of the PR to make more clear that this is significant/make clear what it does. I also updated the main README.md to (a) correct WHERE in the changelog this is listed (it was listed as "changes in a release" but the changes are not yet incorporated into a tagged/versioned release), and (b) make more clear that this is a major change that affects the analysis and performance statistics. 

This should be resolved now, I believe, so I will merge it.

2023-10-24 21:47 UTC, davidlmobley approved these changes

2023-10-24 21:47 UTC, merged